######################################################################
# Automatically generated by qmake (2.01a) mar. sept. 16 08:22:18 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Include Src
INCLUDEPATH += . Include

# Input
HEADERS += Include/enums.h Include/paintArea.h Include/paintWindow.h
SOURCES += Src/main.cpp Src/paintArea.cpp Src/paintWindow.cpp
RESOURCES += PaintWindow.qrc
